config/routes.rb
Rails.application.routes.draw do
root :to => 'login#index'
get 'login',to: 'login#index'
post 'login', to: 'login#check'
get '/register', to: 'register#new'
post "register/create" 
get '/login', to: 'login#sample'
post 'login', to: 'login#new'
  
resources :microposts
#root :to => 'microposts#index'
get '/microposts/:id', to: 'microposts#new'
post  '/microposts/:user_id', to: 'microposts#create'
post '/microposts/:id/edit', to: 'microposts#edit'
get '/microposts', to:   'microposts#show'
put '/microposts/:id', to: 'microposts#update'
delete '/microposts/:id', to:   'microposts#destroy'

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
    belongs_to :user
    
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :microposts, foreign_key: "user_id"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/login_controller.rb
class LoginController < ApplicationController

  def index
    
  end
  
  def check
    @name = params[:name]
    @pass = params[:password]  
    @yes = User.find_by(name: @name, password: @pass)
    $user= @yes.id
    puts @user
    if @yes
      render :action => 'check',:name=>@name,:user_id=> $user
    else
      render :action => 'sample'
    end
  end
  
  def next
    
  end
  
  
  def sample
    
  end
  
  
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
    def index
    #@posts = Micropost.where(user: params[:user_id])
    @posts = Micropost.all
    if @posts
    render :action => 'index',:user_id=> $user
    end
  end

  def new
    @post = Micropost.new params[:id]
  end

  def create
    @post = Micropost.new(micropost_params)
    
    if @post.save
      redirect_to action: 'index',user_id: $user
    else
      render :action => 'new'
    end
  end

  def edit
    @post = Micropost.find params[:id]
  end

  def update
    @post = Micropost.find params[:id]
    if @post.update_attributes params.require(:micropost).permit(:name,:body,:user_id)
       redirect_to action: 'index',user_id: $user
    else
      render :action => :edit
    end
  end

  def destroy
    @post = Micropost.find params[:id]
    @post.destroy
    redirect_to action: 'index',user_id: $user
  end

  def show
    @post = Micropost.find params[:id]
  end
  private

  def micropost_params
    user_id=$user
    puts "chandraaaaaaaaaaaaaaaaaaaaaaaaaaaa"
    puts user_id
    params.require(:micropost).permit(:name,:body,:user_id)
  end
end

app/controllers/register_controller.rb
class RegisterController < ApplicationController
  def new
     @details=User.new
  end
  def create
    @details = User.new(params.permit(:name,:password,:email,:mobile,:age,:address))
    if @details.save
      redirect_to controller: 'login', action: 'index'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/micropost_helper.rb
module MicropostHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/register_helper.rb
module RegisterHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ravi</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/login/check.html.erb
<!DOCTYPE html>
<html>		
<body>
<h1>hai <%= @name %> </h1>

<h1>your loged into your account</h1>
<%= link_to 'Want to get all Quotes', {:controller =>'microposts',:action => 'index',:user_id => $user},{class: 'button'} %>
<p></p><%= link_to 'Logout', {:action => 'index'},{class: 'button'} %></p>
</body>
</html>

app/views/login/index.html.erb
<!DOCTYPE html>
<html>
<body>
<div class="ravi">
	
	

<h2 style="text-align: center;color: blue">Login Form</h2>
<%= form_tag("/login", method: "post") do %>
<center>
  <div class="container"> 
    <label style="color:blue !important;"><b>name</b></label>
    <input type="text" placeholder="Enter name" name="name" required>
    <label style="color:blue !important;"><b>Password</b></label>
    <input type="password" placeholder="Enter Password" name="password" required>
        
    <button type="submit">Login</button>
    <input type="checkbox" checked="checked" style="float:left !important"> <span style="float:left !important">Remember me</span>
    <span class="psw">Forgot <a href="#">password?</a></span>
  </div>
  <div style="margin-top: 20px;text-align: center;width:750px">
    <button type="button" class="cancelbtn" style="float:left !important">Cancel</button>
  </div>
</center>
<% end -%>
<%= form_tag("/register", method: "get") do %>
<center>
<div style="text-align: center;width:750px">
 <button type="submit" class="cancelbtn" style="float:right !important">Register</button>
 </div>
 </center>
 <div style="margin-top: 400px"></div>
 <% end -%>
 </div>
</body>
</html>

app/views/login/next.html.erb
<!DOCTYPE html>
<html>
<body>

<h2>registration form conform</h2>

</body>
</html>

app/views/login/sample.html.erb
<!DOCTYPE html>
<html>
<h1>your enterd wrong details </h1>

<%= link_to 'Please try again', {:action => 'index'},{class: 'button'}  %>
</html>

app/views/microposts/edit.html.erb
<%= form_for @post,:url =>{:action => "update", :id =>@post} do |form| %>
<h1>Author Name</h1>
 <%= form.text_field :name,class: 'text_field'%></br>
 <h1>Quote</h1>
 <%= form.text_area :body,class: 'text_field' %></br>
 <%= form.submit 'Update', :class => 'button' %>
<% end -%>

app/views/microposts/index.html.erb
<h1>List of Quotes</h1>
<table id="customers" border="1">
  <thead>
    <tr>
      <th>Author Name</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
  </thead>
<%  @posts.each do |post| %>
  <tr>
     <td><%= link_to post.name,{:action => "show", :id => post.id} %></td>
     <td><%= button_to 'Edit/Add More', {:action => "edit",:id => post.id},{class: 'button'} %></td> 
	 <td> <%= button_to 'Delete', micropost_path(post),
	                                   method: :delete, 
	                                   class: :button,             
									   data: { confirm: 'Are you sure?' }%></td> 
  </tr>
<% end %>
</table>
<br/>
<%= link_to 'New Quote', {:action => 'new',:user_id=> $user},{class: 'button'} %>
<%= link_to 'Logout', {:controller =>'login',:action => 'index'},{class: 'button'} %> 

app/views/microposts/new.html.erb
<%= form_for @post,:url =>{:action => "create", :id =>@post} do |form| %>
<h1>Author Name</h1>
 <%= form.text_field :name ,class: 'text_field', :required => true  %></br>
 <h1>Quote</h1>
 <%= form.text_area :body,class: 'text_field' %></br>
 <%= form.submit 'Create', :class => 'button' %>
 <%= link_to 'Back', {:action => 'index',:user_id => $user},{class: 'button'} %>
<% end -%>

app/views/microposts/show.html.erb
<h1><%= @post.name %></h1>

<h><%= @post.body %></h></br></br>


<%= link_to 'Edit/Add More', {:action => 'edit'},{class: 'button'} %></br></br>

<%= link_to 'Back to Home', {:action => 'index',:user_id => $user},{class: 'button'} %></br>

<p><%= link_to 'New Quote', {:action => 'new',:user_id=> $user},{class: 'button'} %></p>

app/views/register/new.html.erb
<!DOCTYPE html>
<html>
<body>

<h2 style="text-align: center">Registration  Form</h2>
<%= form_tag :action => 'create' %>
<center>
  <div class="container"> 
    <label style="float:left !important"><b>name</b></label>
    <input type="text" placeholder="Enter name" name="name" required>
    <label style="float:left !important"><b>Password</b></label>
    <input type="password" placeholder="Enter Password" name="password" required> 
    <label style="float:left !important"><b>email</b></label> 
    <input type="text" placeholder="Enter email" name="email" required>
    <label style="float:left !important"><b>phone</b></label> 
    <input type="text" placeholder="Enter phone" name="mobile" required>
    <label style="float:left !important"><b>Age</b></label> 
    <input type="text" placeholder="Enter age" name="age" required>
    <label style="float:left !important"><b>Address</b></label> 
    <input type="text" placeholder="Enter address" name="address" required>       
    <button type="submit">Register</button>  
    <%= link_to 'Already Have an Account? Go Back to Login', {:controller =>'login',:action => 'index'} %> 
  </div> 
</center>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>